version: '3'

services:
  payment-gateway-integrator:
    image: buuhvprojects/payment-gateway-integrator:${IMAGE_VERSION}
    build:
      context: .
    restart: always
    env_file: .env
    container_name: payment-gateway-integrator
    ports:
      - "${PORT}:${PORT}"